logging:
  level:
    root: warn
    home: debug
    org.springframework: info

server:
  port: 8076

spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://connect.test2.surfconext.nl/oidc/introspect
#          introspection-uri: http://localhost:8081/introspect
          client-id: student.mobility.home.institution.mock.local
#          client-id: resource-server-playground-client
          client-secret: secret
